name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: format, lint and type-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
          version: "0.4.10"
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Check code formatting
        run: uvx ruff format --check
      - name: Lint
        run: uvx ruff check
      - name: Type-check
        run: uv run mypy .
      - name: Test
        run: uv run pytest
